### ISSUE TITLE
when I reinstall prelude and some errors with Eager

### ISSUE THREAD

**Issue by Sn0rt** [bbatsov/prelude#966]
➜  .emacs.d git:(ebd6e9d) ✗ ems

Warning: due to a long standing Gtk+ bug
http://bugzilla.gnome.org/show_bug.cgi?id=85715
Emacs might crash when run in daemon mode and the X11 connection is unexpectedly lost.
Using an Emacs configured with --with-x-toolkit=lucid does not have this problem.
Loading /usr/share/emacs/site-lisp/site-start.d/autoconf-init.el (source)...
Loading /usr/share/emacs/site-lisp/site-start.d/autoconf-init.el (source)...done
Loading /usr/share/emacs/site-lisp/site-start.d/desktop-entry-mode-init.el (source)...
Loading /usr/share/emacs/site-lisp/site-start.d/desktop-entry-mode-init.el (source)...done
Loading /usr/share/emacs/site-lisp/site-start.d/git-init.el (source)...
Loading /usr/share/emacs/site-lisp/site-start.d/git-init.el (source)...done
Loading /usr/share/emacs/site-lisp/site-start.d/systemtap-init.el (source)...
Loading /usr/share/emacs/site-lisp/site-start.d/systemtap-init.el (source)...done
Prelude is powering up... Be patient, Master Sn0rt!
Loading personal configuration files in /home/Sn0rt/.emacs.d/personal/preload...
Loading /home/Sn0rt/.emacs.d/personal/preload/c-hook.el (source)...
Loading /home/Sn0rt/.emacs.d/personal/preload/c-hook.el (source)...done
Loading Prelude's core...
ad-handle-definition: `ido-completing-read' got redefined
##### Eager macro-expansion failure: (error "Autoloading failed to define function with-helm-current-buffer")

Loading /home/Sn0rt/.emacs.d/savefile/recentf...
Loading /home/Sn0rt/.emacs.d/savefile/recentf...done
Loading Prelude's modules...
Loading /home/Sn0rt/.emacs.d/prelude-modules.el (source)...
Key Chord mode on
Loading /home/Sn0rt/.emacs.d/prelude-modules.el (source)...done
Loading personal configuration files in /home/Sn0rt/.emacs.d/personal...
Loading /home/Sn0rt/.emacs.d/personal/custom.el (source)...
Loading /home/Sn0rt/.emacs.d/personal/custom.el (source)...done
Prelude is ready to do thy bidding, Master Sn0rt!
Starting Emacs daemon.

**Comment by antmak** [comment]
I think, Eager-error not affect on crash, but its annoying error message.

**Comment by mravery** [comment]
I have the same issue here:

>  ad-handle-definition: `ido-completing-read' got redefined
> #####Eager macro-expansion failure: (error "Autoloading failed to define function helm-build-sync-source")
> #####Eager macro-expansion failure: (error "Autoloading failed to define function with-helm-current-buffer")

Were you able to resolve this?

**Comment by Mestelan** [comment]
Got the same error; resolved by manually installing helm (from melpa).

**Comment by mravery** [comment]
Just for reference, this issue is coming from `imenu-anywhere.el`, lines 227 and 228.

**Comment by liuchong** [comment]
what can we do about this issue?

**Comment by mravery** [comment]
I was able to fix this by updaing the packages first. So:

1. Download and install `prelude`.
1. Open up emacs and update your packages.
1. Restart emacs.

**Comment by liuchong** [comment]
updated, seems the error still there:
Eager macro-expansion failure: (error "Autoloading failed to define function helm-build-sync-source")
Eager macro-expansion failure: (error "Autoloading failed to define function with-helm-current-buffer")
